# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: workflow test

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  actions-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: write
      packages: write

    steps:
# refs/tags/v1.1.4
      - name: Get Tags
        run: |
          tag=${{ github.event.ref }}
          THIS_TAG=${tag##*/}
          echo "THIS_TAG=${HIS_TAG}" >> "$GITHUB_ENV"
          echo "${THIS_TAG}"
          if [ -z "${THIS_TAG}" ]; then
            echo "error: invalid tags"
            exit 1
          fi 

      - name: Checkout repository
        uses: actions/checkout@v4     

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{env.THIS_TAG}}
          release_name: Release ${{env.THIS_TAG}}
          draft: false
          prerelease: false
          make_latest: true
          files: |
            test.tar.gz