# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: workflow test

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  actions-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: test
        run: |
          echo "$(uname -a)"
          sudo apt install shc
          CFLAGS=-static shc -r -f test.sh
          ./test.sh.x
      - name: publish release
        uses: ncipollo/release-action@v1
        with:
           artifacts: "test.sh.x"
           tag: "v1.1.1"
 

